In [1]:
import re
import pandas as pd
import os

FILES = {
    ("x86",     "o0"): "../data/x86_64_o0.ll",
    ("x86",     "o3"): "../data/x86_64_o3.ll",
    ("aarch64", "o0"): "../data/aarch64_o0.ll",
    ("aarch64", "o3"): "../data/aarch64_o3.ll",
}

OP_SUFFIX = {
    "encrypt":          "encrypt_block_64_128",
    "encrypt_inflight": "encrypt_block_inflight_64_128",
    "decrypt":          "decrypt_block_64_128",
}
SPEC = []
for grp in ["scalar", "sse2", "avx2", "avx512", "neon"]:
    for op, suffix in OP_SUFFIX.items():
        SPEC.append((grp, op, f"{grp}_{suffix}"))

TARGETS = [name for _, _, name in SPEC]

HEAP_RE        = re.compile(r"@(__rust_(?:alloc|realloc|dealloc|alloc_zeroed))\b")
ARRAY_RE       = re.compile(r"alloca\s+\[(\d+)\s+x\s+i8\]")
ALLOC_SIZE_RE  = re.compile(r"@__rust_alloc(?:_zeroed)?\(i64 (\d+)")
REALLOC_SIZE_RE= re.compile(r"@__rust_realloc\(.*i64 (\d+)\s*\)")

def heap_bytes(line):
    m = ALLOC_SIZE_RE.search(line) or REALLOC_SIZE_RE.search(line)
    return int(m.group(1)) if m else 0

In [2]:
def parse_ir(path):
    lines = open(path).read().splitlines()
    found = {}
    raw_rows = []
    pending, i, n = [], 0, len(lines)

    while i < n:
        line = lines[i]; st = line.strip()
        if st == "":
            pending = []
        elif st.startswith(";"):
            pending.append(st.lstrip("; ").rstrip())
        elif line.startswith("define"):
            name = next((c for c in reversed(pending)
                         if not c.startswith("Function Attrs")), "<unknown>")
            body, j = [line], i + 1
            while j < n and not lines[j].startswith("}"):
                body.append(lines[j]); j += 1
            match = next((t for t in TARGETS if t in name), None)
            if match and match not in found:
                allocas = [b.strip() for b in body if "alloca" in b]
                heaps   = [b.strip() for b in body if HEAP_RE.search(b)]
                found[match] = dict(
                    mangled=name,
                    alloca_count=len(allocas),
                    stack_bytes=sum(int(m.group(1)) for b in allocas
                                    if (m := ARRAY_RE.search(b))),
                    heap_count=len(heaps),
                    heap_bytes=sum(heap_bytes(b) for b in heaps),
                )
                for a in allocas:
                    m = ARRAY_RE.search(a)
                    raw_rows.append(dict(func=match, kind="stack",
                                         bytes=int(m.group(1)) if m else None,
                                         ir=a))
                for h in heaps:
                    raw_rows.append(dict(func=match, kind="heap",
                                         bytes=heap_bytes(h) or None,
                                         ir=h))
            pending, i = [], j
        i += 1

    summary = []
    for grp, op, name in SPEC:
        d = found.get(name)
        summary.append(dict(
            group=grp, op=op, func=name, present=d is not None,
            alloca_count=d["alloca_count"] if d else 0,
            stack_bytes =d["stack_bytes"]  if d else 0,
            heap_count  =d["heap_count"]   if d else 0,
            heap_bytes  =d["heap_bytes"]   if d else 0,
            mangled     =d["mangled"]      if d else None,
        ))
    df = pd.DataFrame(summary)
    raw = pd.DataFrame(raw_rows, columns=["func", "kind", "bytes", "ir"])
    return df, raw

In [3]:
dfs, raws = [], []
for (arch, opt), path in FILES.items():
    d, r = parse_ir(path)
    d.insert(0, "arch", arch); d.insert(1, "opt", opt)
    r.insert(0, "arch", arch); r.insert(1, "opt", opt)
    dfs.append(d); raws.append(r)

df  = pd.concat(dfs,  ignore_index=True)
raw = pd.concat(raws, ignore_index=True)

df["arch"]  = pd.Categorical(df["arch"],  categories=["x86","aarch64"], ordered=True)
df["opt"]   = pd.Categorical(df["opt"],   categories=["o0","o3"], ordered=True)
df["group"] = pd.Categorical(df["group"],
                categories=["scalar","sse2","avx2","avx512","neon"], ordered=True)
df["op"]    = pd.Categorical(df["op"],
                categories=["encrypt","encrypt_inflight","decrypt"], ordered=True)
df = df.sort_values(["arch","opt","group","op"]).reset_index(drop=True)

In [4]:
present = df[df.present].drop(columns=["present","mangled"])
present

,arch,opt,group,op,func,alloca_count,stack_bytes,heap_count,heap_bytes
0,x86,o0,scalar,encrypt,scalar_encrypt_block_64_128,8,156,0,0
1,x86,o0,scalar,encrypt_inflight,scalar_encrypt_block_inflight_64_128,7,48,0,0
2,x86,o0,scalar,decrypt,scalar_decrypt_block_64_128,8,156,0,0
3,x86,o0,sse2,encrypt,sse2_encrypt_block_64_128,1251,20464,0,0
4,x86,o0,sse2,encrypt_inflight,sse2_encrypt_block_inflight_64_128,1249,20016,0,0
5,x86,o0,sse2,decrypt,sse2_decrypt_block_64_128,1251,20464,0,0
6,x86,o0,avx2,encrypt,avx2_encrypt_block_64_128,1251,40928,0,0
7,x86,o0,avx2,encrypt_inflight,avx2_encrypt_block_inflight_64_128,1249,40032,0,0
8,x86,o0,avx2,decrypt,avx2_decrypt_block_64_128,1251,40928,0,0
9,x86,o0,avx512,encrypt,avx512_encrypt_block_64_128,721,47936,0,0
10,x86,o0,avx512,encrypt_inflight,avx512_encrypt_block_inflight_64_128,719,46144,0,0
11,x86,o0,avx512,decrypt,avx512_decrypt_block_64_128,721,47936,0,0
15,x86,o3,scalar,encrypt,scalar_encrypt_block_64_128,0,0,0,0
16,x86,o3,scalar,encrypt_inflight,scalar_encrypt_block_inflight_64_128,0,0,0,0
17,x86,o3,scalar,decrypt,scalar_decrypt_block_64_128,0,0,0,0
18,x86,o3,sse2,encrypt,sse2_encrypt_block_64_128,0,0,0,0
19,x86,o3,sse2,encrypt_inflight,sse2_encrypt_block_inflight_64_128,0,0,0,0
20,x86,o3,sse2,decrypt,sse2_decrypt_block_64_128,0,0,0,0
21,x86,o3,avx2,encrypt,avx2_encrypt_block_64_128,0,0,0,0
22,x86,o3,avx2,encrypt_inflight,avx2_encrypt_block_inflight_64_128,0,0,0,0
23,x86,o3,avx2,decrypt,avx2_decrypt_block_64_128,0,0,0,0
24,x86,o3,avx512,encrypt,avx512_encrypt_block_64_128,0,0,0,0
25,x86,o3,avx512,encrypt_inflight,avx512_encrypt_block_inflight_64_128,0,0,0,0
26,x86,o3,avx512,decrypt,avx512_decrypt_block_64_128,0,0,0,0
30,aarch64,o0,scalar,encrypt,scalar_encrypt_block_64_128,8,156,0,0
31,aarch64,o0,scalar,encrypt_inflight,scalar_encrypt_block_inflight_64_128,7,48,0,0
32,aarch64,o0,scalar,decrypt,scalar_decrypt_block_64_128,8,156,0,0
42,aarch64,o0,neon,encrypt,neon_encrypt_block_64_128,1251,20464,0,0
43,aarch64,o0,neon,encrypt_inflight,neon_encrypt_block_inflight_64_128,1249,20016,0,0
44,aarch64,o0,neon,decrypt,neon_decrypt_block_64_128,1251,20464,0,0
45,aarch64,o3,scalar,encrypt,scalar_encrypt_block_64_128,0,0,0,0
46,aarch64,o3,scalar,encrypt_inflight,scalar_encrypt_block_inflight_64_128,0,0,0,0
47,aarch64,o3,scalar,decrypt,scalar_decrypt_block_64_128,0,0,0,0
57,aarch64,o3,neon,encrypt,neon_encrypt_block_64_128,0,0,0,0
58,aarch64,o3,neon,encrypt_inflight,neon_encrypt_block_inflight_64_128,0,0,0,0
59,aarch64,o3,neon,decrypt,neon_decrypt_block_64_128,0,0,0,0

In [5]:
present.pivot_table(
    index=["group","op"], columns=["arch","opt"],
    values="stack_bytes", observed=True
)

arch                         x86       aarch64
opt                           o0   o3       o0   o3
group  op
scalar encrypt             156.0  0.0    156.0  0.0
       encrypt_inflight     48.0  0.0     48.0  0.0
       decrypt             156.0  0.0    156.0  0.0
sse2   encrypt           20464.0  0.0      NaN  NaN
       encrypt_inflight  20016.0  0.0      NaN  NaN
       decrypt           20464.0  0.0      NaN  NaN
avx2   encrypt           40928.0  0.0      NaN  NaN
       encrypt_inflight  40032.0  0.0      NaN  NaN
       decrypt           40928.0  0.0      NaN  NaN
avx512 encrypt           47936.0  0.0      NaN  NaN
       encrypt_inflight  46144.0  0.0      NaN  NaN
       decrypt           47936.0  0.0      NaN  NaN
neon   encrypt               NaN  NaN  20464.0  0.0
       encrypt_inflight      NaN  NaN  20016.0  0.0
       decrypt               NaN  NaN  20464.0  0.0

In [6]:
present.groupby(["arch","opt","group"], observed=True)[
    ["alloca_count","stack_bytes","heap_count","heap_bytes"]].sum()

                    alloca_count  stack_bytes  heap_count  heap_bytes
arch    opt group
x86     o0  scalar            23          360           0           0
            sse2            3751        60944           0           0
            avx2            3751       121888           0           0
            avx512          2161       142016           0           0
        o3  scalar             0            0           0           0
            sse2               0            0           0           0
            avx2               0            0           0           0
            avx512             0            0           0           0
aarch64 o0  scalar            23          360           0           0
            neon            3751        60944           0           0
        o3  scalar             0            0           0           0
            neon               0            0           0           0

In [7]:
backend_map = {
    "scalar": "Skalarny",
    "sse2":   "SSE2",
    "avx2":   "AVX2",
    "avx512": "AVX-512",
    "neon":   "NEON",
}

op_map = {
    "encrypt":          "Szyfrowanie",
    "encrypt_inflight": "Szyfr. w locie",
    "decrypt":          "Deszyfrowanie",
}

arch_map = {
    "x86": "x86\_64",
}

<>:16: SyntaxWarning: "\_" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\_"? A raw string is also an option.
<>:16: SyntaxWarning: "\_" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\_"? A raw string is also an option.
/tmp/ipykernel_47855/3940724603.py:16: SyntaxWarning: "\_" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\_"? A raw string is also an option.
  "x86": "x86\_64",

In [8]:
table = (present.groupby(["arch","opt","group","op"], observed=True)[
            ["alloca_count","stack_bytes","heap_count","heap_bytes"]].sum()
         .unstack("opt")
         .swaplevel(axis=1)
         .sort_index(axis=1))

table = table.drop(columns=["heap_count", "heap_bytes"], level=1)

table = table.rename(index=arch_map,    level="arch")
table = table.rename(index=backend_map, level="group")
table = table.rename(index=op_map,      level="op")

os.makedirs("../csv", exist_ok=True)

out = table.copy()
out.columns = ["_".join(map(str, c)) for c in out.columns]
out = out.reset_index()
out.to_csv("../csv/memory_results.csv", index=False)

In [9]:
def print_raw(arch, opt, kinds=("stack", "heap")):
    sub = raw[(raw.arch == arch) & (raw.opt == opt)]
    print("=" * 70)
    print(f" {arch}  {opt}")
    print("=" * 70)
    for grp, op, name in SPEC:
        d = df[(df.arch == arch) & (df.opt == opt) & (df.func == name)]
        if d.empty or not bool(d.present.iloc[0]):
            continue
        r0 = d.iloc[0]
        rows = sub[sub.func == name]
        print(f"\n=== [{grp}/{op}] {r0.mangled}")
        if "stack" in kinds:
            print(f"   stos:   {r0.alloca_count} alloca, >= {r0.stack_bytes} B")
            for ir in rows[rows.kind == "stack"].ir:
                print(f"            {ir}")
        if "heap" in kinds:
            print(f"   sterta: {r0.heap_count} wywolan, >= {r0.heap_bytes} B")
            for ir in rows[rows.kind == "heap"].ir:
                print(f"            {ir}")

In [10]:
print_raw("x86", "o0")

======================================================================
 x86  o0
======================================================================

=== [scalar/encrypt] speck_probe::speck::backend::scalar::encrypt_block::scalar_encrypt_block_64_128
   stos:   8 alloca, >= 156 B
            %y = alloca [4 x i8], align 4
            %x = alloca [4 x i8], align 4
            %k = alloca [4 x i8], align 4
            %l = alloca [12 x i8], align 4
            %round_keys = alloca [108 x i8], align 4
            %_0 = alloca [8 x i8], align 4
            %1 = alloca [8 x i8], align 8
            %ct = alloca [8 x i8], align 4
   sterta: 0 wywolan, >= 0 B

=== [scalar/encrypt_inflight] speck_probe::speck::backend::scalar::encrypt_block::scalar_encrypt_block_inflight_64_128
   stos:   7 alloca, >= 48 B
            %y = alloca [4 x i8], align 4
            %x = alloca [4 x i8], align 4
            %k = alloca [4 x i8], align 4
            %l = alloca [12 x i8], align 4
            %_0 = alloca [8 x i8], align 4
            %1 = alloca [8 x i8], align 8
            %ct = alloca [8 x i8], align 4
   sterta: 0 wywolan, >= 0 B

=== [scalar/decrypt] speck_probe::speck::backend::scalar::decrypt_block::scalar_decrypt_block_64_128
   stos:   8 alloca, >= 156 B
            %y = alloca [4 x i8], align 4
            %x = alloca [4 x i8], align 4
            %k = alloca [4 x i8], align 4
            %l = alloca [12 x i8], align 4
            %round_keys = alloca [108 x i8], align 4
            %_0 = alloca [8 x i8], align 4
            %1 = alloca [8 x i8], align 8
            %ct = alloca [8 x i8], align 4
   sterta: 0 wywolan, >= 0 B

=== [sse2/encrypt] speck_probe::speck::backend::x86_64::sse2::encrypt_block::sse2_encrypt_block_64_128
   stos:   1251 alloca, >= 20464 B
            %0 = alloca [16 x i8], align 16
            %1 = alloca [16 x i8], align 16
            %2 = alloca [16 x i8], align 16
            %3 = alloca [16 x i8], align 16
            %4 = alloca [16 x i8], align 16
            %5 = alloca [16 x i8], align 16
            %6 = alloca [16 x i8], align 16
            %7 = alloca [16 x i8], align 16
            %8 = alloca [16 x i8], align 16
            %9 = alloca [16 x i8], align 16
            %10 = alloca [16 x i8], align 16
            %11 = alloca [16 x i8], align 16
            %12 = alloca [16 x i8], align 16
            %13 = alloca [16 x i8], align 16
            %14 = alloca [16 x i8], align 16
            %15 = alloca [16 x i8], align 16
            %16 = alloca [16 x i8], align 16
            %17 = alloca [16 x i8], align 16
            %18 = alloca [16 x i8], align 16
            %19 = alloca [16 x i8], align 16
            %20 = alloca [16 x i8], align 16
            %21 = alloca [16 x i8], align 16
            %22 = alloca [16 x i8], align 16
            %23 = alloca [16 x i8], align 16
            %24 = alloca [16 x i8], align 16
            %25 = alloca [16 x i8], align 16
            %26 = alloca [16 x i8], align 16
            %27 = alloca [16 x i8], align 16
            %28 = alloca [16 x i8], align 16
            %29 = alloca [16 x i8], align 16
            %30 = alloca [16 x i8], align 16
            %31 = alloca [16 x i8], align 16
            %32 = alloca [16 x i8], align 16
            %33 = alloca [16 x i8], align 16
            %34 = alloca [16 x i8], align 16
            %35 = alloca [16 x i8], align 16
            %36 = alloca [16 x i8], align 16
            %37 = alloca [16 x i8], align 16
            %38 = alloca [16 x i8], align 16
            %39 = alloca [16 x i8], align 16
            %40 = alloca [16 x i8], align 16
            %41 = alloca [16 x i8], align 16
            %42 = alloca [16 x i8], align 16
            %43 = alloca [16 x i8], align 16
            %44 = alloca [16 x i8], align 16
            %45 = alloca [16 x i8], align 16
            %46 = alloca [16 x i8], align 16
            %47 = alloca [16 x i8], align 16
            %48 = alloca [16 x i8], align 16
            %49 = alloca [16 x i8], align 16
            %50 = alloca [16 x i8], align 16
            %51 = alloca [16 x i8], align 16
            %52 = alloca [16 x i8], align 16
            %53 = alloca [16 x i8], align 16
            %54 = alloca [16 x i8], align 16
            %55 = alloca [16 x i8], align 16
            %56 = alloca [16 x i8], align 16
            %57 = alloca [16 x i8], align 16
            %58 = alloca [16 x i8], align 16
            %59 = alloca [16 x i8], align 16
            %60 = alloca [16 x i8], align 16
            %61 = alloca [16 x i8], align 16
            %62 = alloca [16 x i8], align 16
            %63 = alloca [16 x i8], align 16
            %64 = alloca [16 x i8], align 16
            %65 = alloca [16 x i8], align 16
            %66 = alloca [16 x i8], align 16
            %67 = alloca [16 x i8], align 16
            %68 = alloca [16 x i8], align 16
            %69 = alloca [16 x i8], align 16
            %70 = alloca [16 x i8], align 16
            %71 = alloca [16 x i8], align 16
            %72 = alloca [16 x i8], align 16
            %73 = alloca [16 x i8], align 16
            %74 = alloca [16 x i8], align 16
            %75 = alloca [16 x i8], align 16
            %76 = alloca [16 x i8], align 16
            %77 = alloca [16 x i8], align 16
            %78 = alloca [16 x i8], align 16
            %79 = alloca [16 x i8], align 16
            %80 = alloca [16 x i8], align 16
            %81 = alloca [16 x i8], align 16
            %82 = alloca [16 x i8], align 16
            %83 = alloca [16 x i8], align 16
            %84 = alloca [16 x i8], align 16
            %85 = alloca [16 x i8], align 16
            %86 = alloca [16 x i8], align 16
            %87 = alloca [16 x i8], align 16
            %88 = alloca [16 x i8], align 16
            %89 = alloca [16 x i8], align 16
            %90 = alloca [16 x i8], align 16
            %91 = alloca [16 x i8], align 16
            %92 = alloca [16 x i8], align 16
            %93 = alloca [16 x i8], align 16
            %94 = alloca [16 x i8], align 16
            %95 = alloca [16 x i8], align 16
            %96 = alloca [16 x i8], align 16
            %97 = alloca [16 x i8], align 16
            %98 = alloca [16 x i8], align 16
            %99 = alloca [16 x i8], align 16
            %100 = alloca [16 x i8], align 16
            %101 = alloca [16 x i8], align 16
            %102 = alloca [16 x i8], align 16
            %103 = alloca [16 x i8], align 16
            %104 = alloca [16 x i8], align 16
            %105 = alloca [16 x i8], align 16
            %106 = alloca [16 x i8], align 16
            %107 = alloca [16 x i8], align 16
            %108 = alloca [16 x i8], align 16
            %109 = alloca [16 x i8], align 16
            %110 = alloca [16 x i8], align 16
            %111 = alloca [16 x i8], align 16
            %112 = alloca [16 x i8], align 16
            %113 = alloca [16 x i8], align 16
            %114 = alloca [16 x i8], align 16
            %115 = alloca [16 x i8], align 16
            %116 = alloca [16 x i8], align 16
            %117 = alloca [16 x i8], align 16
            %118 = alloca [16 x i8], align 16
            %119 = alloca [16 x i8], align 16
            %120 = alloca [16 x i8], align 16
            %121 = alloca [16 x i8], align 16
            %122 = alloca [16 x i8], align 16
            %123 = alloca [16 x i8], align 16
            %124 = alloca [16 x i8], align 16
            %125 = alloca [16 x i8], align 16
            %126 = alloca [16 x i8], align 16
            %127 = alloca [16 x i8], align 16
            %128 = alloca [16 x i8], align 16
            %129 = alloca [16 x i8], align 16
            %130 = alloca [16 x i8], align 16
            %131 = alloca [16 x i8], align 16
            %132 = alloca [16 x i8], align 16
            %133 = alloca [16 x i8], align 16
            %134 = alloca [16 x i8], align 16
            %135 = alloca [16 x i8], align 16
            %136 = alloca [16 x i8], align 16
            %137 = alloca [16 x i8], align 16
            %138 = alloca [16 x i8], align 16
            %139 = alloca [16 x i8], align 16
            %140 = alloca [16 x i8], align 16
            %141 = alloca [16 x i8], align 16
            %142 = alloca [16 x i8], align 16
            %143 = alloca [16 x i8], align 16
            %144 = alloca [16 x i8], align 16
            %145 = alloca [16 x i8], align 16
            %146 = alloca [16 x i8], align 16
            %147 = alloca [16 x i8], align 16
            %148 = alloca [16 x i8], align 16
            %149 = alloca [16 x i8], align 16
            %150 = alloca [16 x i8], align 16
            %151 = alloca [16 x i8], align 16
            %152 = alloca [16 x i8], align 16
            %153 = alloca [16 x i8], align 16
            %154 = alloca [16 x i8], align 16
            %155 = alloca [16 x i8], align 16
            %156 = alloca [16 x i8], align 16
            %157 = alloca [16 x i8], align 16
            %158 = alloca [16 x i8], align 16
            %159 = alloca [16 x i8], align 16
            %160 = alloca [16 x i8], align 16
            %161 = alloca [16 x i8], align 16
            %162 = alloca [16 x i8], align 16
            %163 = alloca [16 x i8], align 16
            %164 = alloca [16 x i8], align 16
            %165 = alloca [16 x i8], align 16
            %166 = alloca [16 x i8], align 16
            %167 = alloca [16 x i8], align 16
            %168 = alloca [16 x i8], align 16
            %169 = alloca [16 x i8], align 16
            %170 = alloca [16 x i8], align 16
            %171 = alloca [16 x i8], align 16
            %172 = alloca [16 x i8], align 16
            %173 = alloca [16 x i8], align 16
            %174 = alloca [16 x i8], align 16
            %175 = alloca [16 x i8], align 16
            %176 = alloca [16 x i8], align 16
            %177 = alloca [16 x i8], align 16
            %178 = alloca [16 x i8], align 16
            %179 = alloca [16 x i8], align 16
            %180 = alloca [16 x i8], align 16
            %181 = alloca [16 x i8], align 16
            %182 = alloca [16 x i8], align 16
            %183 = alloca [16 x i8], align 16
            %184 = alloca [16 x i8], align 16
            %185 = alloca [16 x i8], align 16
            %186 = alloca [16 x i8], align 16
            %187 = alloca [16 x i8], align 16
            %188 = alloca [16 x i8], align 16
            %189 = alloca [16 x i8], align 16
            %190 = alloca [16 x i8], align 16
            %191 = alloca [16 x i8], align 16
            %192 = alloca [16 x i8], align 16
            %193 = alloca [16 x i8], align 16
            %194 = alloca [16 x i8], align 16
            %195 = alloca [16 x i8], align 16
            %196 = alloca [16 x i8], align 16
            %197 = alloca [16 x i8], align 16
            %198 = alloca [16 x i8], align 16
            %199 = alloca [16 x i8], align 16
            %200 = alloca [16 x i8], align 16
            %201 = alloca [16 x i8], align 16
            %202 = alloca [16 x i8], align 16
            %203 = alloca [16 x i8], align 16
            %204 = alloca [16 x i8], align 16
            %205 = alloca [16 x i8], align 16
            %206 = alloca [16 x i8], align 16
            %207 = alloca [16 x i8], align 16
            %208 = alloca [16 x i8], align 16
            %209 = alloca [16 x i8], align 16
            %210 = alloca [16 x i8], align 16
            %211 = alloca [16 x i8], align 16
            %212 = alloca [16 x i8], align 16
            %213 = alloca [16 x i8], align 16
            %214 = alloca [16 x i8], align 16
            %215 = alloca [16 x i8], align 16
            %216 = alloca [16 x i8], align 16
            %217 = alloca [16 x i8], align 16
            %218 = alloca [16 x i8], align 16
            %219 = alloca [16 x i8], align 16
            %220 = alloca [16 x i8], align 16
            %221 = alloca [16 x i8], align 16
            %222 = alloca [16 x i8], align 16
            %223 = alloca [16 x i8], align 16
            %224 = alloca [16 x i8], align 16
            %225 = alloca [16 x i8], align 16
            %226 = alloca [16 x i8], align 16
            %227 = alloca [16 x i8], align 16
            %228 = alloca [16 x i8], align 16
            %229 = alloca [16 x i8], align 16
            %230 = alloca [16 x i8], align 16
            %231 = alloca [16 x i8], align 16
            %232 = alloca [16 x i8], align 16
            %233 = alloca [16 x i8], align 16
            %234 = alloca [16 x i8], align 16
            %235 = alloca [16 x i8], align 16
            %236 = alloca [16 x i8], align 16
            %237 = alloca [16 x i8], align 16
            %238 = alloca [16 x i8], align 16
            %239 = alloca [16 x i8], align 16
            %240 = alloca [16 x i8], align 16
            %241 = alloca [16 x i8], align 16
            %242 = alloca [16 x i8], align 16
            %243 = alloca [16 x i8], align 16
            %244 = alloca [16 x i8], align 16
            %245 = alloca [16 x i8], align 16
            %246 = alloca [16 x i8], align 16
            %247 = alloca [16 x i8], align 16
            %248 = alloca [16 x i8], align 16
            %249 = alloca [16 x i8], align 16
            %250 = alloca [16 x i8], align 16
            %251 = alloca [16 x i8], align 16
            %252 = alloca [16 x i8], align 16
            %253 = alloca [16 x i8], align 16
            %254 = alloca [16 x i8], align 16
            %255 = alloca [16 x i8], align 16
            %256 = alloca [16 x i8], align 16
            %257 = alloca [16 x i8], align 16
            %258 = alloca [16 x i8], align 16
            %259 = alloca [16 x i8], align 16
            %260 = alloca [16 x i8], align 16
            %261 = alloca [16 x i8], align 16
            %262 = alloca [16 x i8], align 16
            %263 = alloca [16 x i8], align 16
            %264 = alloca [16 x i8], align 16
            %265 = alloca [16 x i8], align 16
            %266 = alloca [16 x i8], align 16
            %267 = alloca [16 x i8], align 16
            %268 = alloca [16 x i8], align 16
            %269 = alloca [16 x i8], align 16
            %270 = alloca [16 x i8], align 16
            %271 = alloca [16 x i8], align 16
            %272 = alloca [16 x i8], align 16
            %273 = alloca [16 x i8], align 16
            %274 = alloca [16 x i8], align 16
            %275 = alloca [16 x i8], align 16
            %276 = alloca [16 x i8], align 16
            %277 = alloca [16 x i8], align 16
            %278 = alloca [16 x i8], align 16
            %279 = alloca [16 x i8], align 16
            %280 = alloca [16 x i8], align 16
            %281 = alloca [16 x i8], align 16
            %282 = alloca [16 x i8], align 16
            %283 = alloca [16 x i8], align 16
            %284 = alloca [16 x i8], align 16
            %285 = alloca [16 x i8], align 16
            %286 = alloca [16 x i8], align 16
            %287 = alloca [16 x i8], align 16
            %288 = alloca [16 x i8], align 16
            %289 = alloca [16 x i8], align 16
            %290 = alloca [16 x i8], align 16
            %291 = alloca [16 x i8], align 16
            %292 = alloca [16 x i8], align 16
            %293 = alloca [16 x i8], align 16
            %294 = alloca [16 x i8], align 16
            %295 = alloca [16 x i8], align 16
            %296 = alloca [16 x i8], align 16
            %297 = alloca [16 x i8], align 16
            %298 = alloca [16 x i8], align 16
            %299 = alloca [16 x i8], align 16
            %300 = alloca [16 x i8], align 16
            %301 = alloca [16 x i8], align 16
            %302 = alloca [16 x i8], align 16
            %303 = alloca [16 x i8], align 16
            %304 = alloca [16 x i8], align 16
            %305 = alloca [16 x i8], align 16
            %306 = alloca [16 x i8], align 16
            %307 = alloca [16 x i8], align 16
            %308 = alloca [16 x i8], align 16
            %309 = alloca [16 x i8], align 16
            %310 = alloca [16 x i8], align 16
            %311 = alloca [16 x i8], align 16
            %312 = alloca [16 x i8], align 16
            %313 = alloca [16 x i8], align 16
            %314 = alloca [16 x i8], align 16
            %315 = alloca [16 x i8], align 16
            %316 = alloca [16 x i8], align 16
            %317 = alloca [16 x i8], align 16
            %318 = alloca [16 x i8], align 16
            %319 = alloca [16 x i8], align 16
            %320 = alloca [16 x i8], align 16
            %321 = alloca [16 x i8], align 16
            %322 = alloca [16 x i8], align 16
            %323 = alloca [16 x i8], align 16
            %324 = alloca [16 x i8], align 16
            %325 = alloca [16 x i8], align 16
            %326 = alloca [16 x i8], align 16
            %327 = alloca [16 x i8], align 16
            %328 = alloca [16 x i8], align 16
            %329 = alloca [16 x i8], align 16
            %330 = alloca [16 x i8], align 16
            %331 = alloca [16 x i8], align 16
            %332 = alloca [16 x i8], align 16
            %333 = alloca [16 x i8], align 16
            %334 = alloca [16 x i8], align 16
            %335 = alloca [16 x i8], align 16
            %336 = alloca [16 x i8], align 16
            %337 = alloca [16 x i8], align 16
            %338 = alloca [16 x i8], align 16
            %339 = alloca [16 x i8], align 16
            %340 = alloca [16 x i8], align 16
            %341 = alloca [16 x i8], align 16
            %342 = alloca [16 x i8], align 16
            %343 = alloca [16 x i8], align 16
            %344 = alloca [16 x i8], align 16
            %345 = alloca [16 x i8], align 16
            %346 = alloca [16 x i8], align 16
            %347 = alloca [16 x i8], align 16
            %348 = alloca [16 x i8], align 16
            %349 = alloca [16 x i8], align 16
            %350 = alloca [16 x i8], align 16
            %351 = alloca [16 x i8], align 16
            %352 = alloca [16 x i8], align 16
            %353 = alloca [16 x i8], align 16
            %354 = alloca [16 x i8], align 16
            %355 = alloca [16 x i8], align 16
            %356 = alloca [16 x i8], align 16
            %357 = alloca [16 x i8], align 16
            %358 = alloca [16 x i8], align 16
            %359 = alloca [16 x i8], align 16
            %360 = alloca [16 x i8], align 16
            %361 = alloca [16 x i8], align 16
            %362 = alloca [16 x i8], align 16
            %363 = alloca [16 x i8], align 16
            %364 = alloca [16 x i8], align 16
            %365 = alloca [16 x i8], align 16
            %366 = alloca [16 x i8], align 16
            %367 = alloca [16 x i8], align 16
            %368 = alloca [16 x i8], align 16
            %369 = alloca [16 x i8], align 16
            %370 = alloca [16 x i8], align 16
            %371 = alloca [16 x i8], align 16
            %372 = alloca [16 x i8], align 16
            %373 = alloca [16 x i8], align 16
            %374 = alloca [16 x i8], align 16
            %375 = alloca [16 x i8], align 16
            %376 = alloca [16 x i8], align 16
            %377 = alloca [16 x i8], align 16
            %378 = alloca [16 x i8], align 16
            %379 = alloca [16 x i8], align 16
            %380 = alloca [16 x i8], align 16
            %381 = alloca [16 x i8], align 16
            %382 = alloca [16 x i8], align 16
            %383 = alloca [16 x i8], align 16
            %384 = alloca [16 x i8], align 16
            %385 = alloca [16 x i8], align 16
            %386 = alloca [16 x i8], align 16
            %387 = alloca [16 x i8], align 16
            %388 = alloca [16 x i8], align 16
            %389 = alloca [16 x i8], align 16
            %390 = alloca [16 x i8], align 16
            %391 = alloca [16 x i8], align 16
            %392 = alloca [16 x i8], align 16
            %393 = alloca [16 x i8], align 16
            %394 = alloca [16 x i8], align 16
            %395 = alloca [16 x i8], align 16
            %396 = alloca [16 x i8], align 16
            %397 = alloca [16 x i8], align 16

In [11]:
print_raw("x86", "o3")

======================================================================
 x86  o3
======================================================================

=== [scalar/encrypt] speck_probe::speck::backend::scalar::encrypt_block::scalar_encrypt_block_64_128
   stos:   0 alloca, >= 0 B
   sterta: 0 wywolan, >= 0 B

=== [scalar/encrypt_inflight] speck_probe::speck::backend::scalar::encrypt_block::scalar_encrypt_block_inflight_64_128
   stos:   0 alloca, >= 0 B
   sterta: 0 wywolan, >= 0 B

=== [scalar/decrypt] speck_probe::speck::backend::scalar::decrypt_block::scalar_decrypt_block_64_128
   stos:   0 alloca, >= 0 B
   sterta: 0 wywolan, >= 0 B

=== [sse2/encrypt] speck_probe::speck::backend::x86_64::sse2::encrypt_block::sse2_encrypt_block_64_128
   stos:   0 alloca, >= 0 B
   sterta: 0 wywolan, >= 0 B

=== [sse2/encrypt_inflight] speck_probe::speck::backend::x86_64::sse2::encrypt_block::sse2_encrypt_block_inflight_64_128
   stos:   0 alloca, >= 0 B
   sterta: 0 wywolan, >= 0 B

=== [sse2/decrypt] speck_probe::speck::backend::x86_64::sse2::decrypt_block::sse2_decrypt_block_64_128
   stos:   0 alloca, >= 0 B
   sterta: 0 wywolan, >= 0 B

=== [avx2/encrypt] speck_probe::speck::backend::x86_64::avx2::encrypt_block::avx2_encrypt_block_64_128
   stos:   0 alloca, >= 0 B
   sterta: 0 wywolan, >= 0 B

=== [avx2/encrypt_inflight] speck_probe::speck::backend::x86_64::avx2::encrypt_block::avx2_encrypt_block_inflight_64_128
   stos:   0 alloca, >= 0 B
   sterta: 0 wywolan, >= 0 B

=== [avx2/decrypt] speck_probe::speck::backend::x86_64::avx2::decrypt_block::avx2_decrypt_block_64_128
   stos:   0 alloca, >= 0 B
   sterta: 0 wywolan, >= 0 B

=== [avx512/encrypt] speck_probe::speck::backend::x86_64::avx512::encrypt_block::avx512_encrypt_block_64_128
   stos:   0 alloca, >= 0 B
   sterta: 0 wywolan, >= 0 B

=== [avx512/encrypt_inflight] speck_probe::speck::backend::x86_64::avx512::encrypt_block::avx512_encrypt_block_inflight_64_128
   stos:   0 alloca, >= 0 B
   sterta: 0 wywolan, >= 0 B

=== [avx512/decrypt] speck_probe::speck::backend::x86_64::avx512::decrypt_block::avx512_decrypt_block_64_128
   stos:   0 alloca, >= 0 B
   sterta: 0 wywolan, >= 0 B

In [12]:
print_raw("aarch64", "o0")

======================================================================
 aarch64  o0
======================================================================

=== [scalar/encrypt] speck_probe::speck::backend::scalar::encrypt_block::scalar_encrypt_block_64_128
   stos:   8 alloca, >= 156 B
            %y = alloca [4 x i8], align 4
            %x = alloca [4 x i8], align 4
            %k = alloca [4 x i8], align 4
            %l = alloca [12 x i8], align 4
            %round_keys = alloca [108 x i8], align 4
            %_0 = alloca [8 x i8], align 4
            %1 = alloca [8 x i8], align 8
            %ct = alloca [8 x i8], align 4
   sterta: 0 wywolan, >= 0 B

=== [scalar/encrypt_inflight] speck_probe::speck::backend::scalar::encrypt_block::scalar_encrypt_block_inflight_64_128
   stos:   7 alloca, >= 48 B
            %y = alloca [4 x i8], align 4
            %x = alloca [4 x i8], align 4
            %k = alloca [4 x i8], align 4
            %l = alloca [12 x i8], align 4
            %_0 = alloca [8 x i8], align 4
            %1 = alloca [8 x i8], align 8
            %ct = alloca [8 x i8], align 4
   sterta: 0 wywolan, >= 0 B

=== [scalar/decrypt] speck_probe::speck::backend::scalar::decrypt_block::scalar_decrypt_block_64_128
   stos:   8 alloca, >= 156 B
            %y = alloca [4 x i8], align 4
            %x = alloca [4 x i8], align 4
            %k = alloca [4 x i8], align 4
            %l = alloca [12 x i8], align 4
            %round_keys = alloca [108 x i8], align 4
            %_0 = alloca [8 x i8], align 4
            %1 = alloca [8 x i8], align 8
            %ct = alloca [8 x i8], align 4
   sterta: 0 wywolan, >= 0 B

=== [neon/encrypt] speck_probe::speck::backend::aarch64::neon::encrypt_block::neon_encrypt_block_64_128
   stos:   1251 alloca, >= 20464 B
            %0 = alloca [16 x i8], align 16
            %1 = alloca [16 x i8], align 16
            %2 = alloca [16 x i8], align 16
            %3 = alloca [16 x i8], align 16
            %4 = alloca [16 x i8], align 16
            %5 = alloca [16 x i8], align 16
            %6 = alloca [16 x i8], align 16
            %7 = alloca [16 x i8], align 16
            %8 = alloca [16 x i8], align 16
            %9 = alloca [16 x i8], align 16
            %10 = alloca [16 x i8], align 16
            %11 = alloca [16 x i8], align 16
            %12 = alloca [16 x i8], align 16
            %13 = alloca [16 x i8], align 16
            %14 = alloca [16 x i8], align 16
            %15 = alloca [16 x i8], align 16
            %16 = alloca [16 x i8], align 16
            %17 = alloca [16 x i8], align 16
            %18 = alloca [16 x i8], align 16
            %19 = alloca [16 x i8], align 16
            %20 = alloca [16 x i8], align 16
            %21 = alloca [16 x i8], align 16
            %22 = alloca [16 x i8], align 16
            %23 = alloca [16 x i8], align 16
            %24 = alloca [16 x i8], align 16
            %25 = alloca [16 x i8], align 16
            %26 = alloca [16 x i8], align 16
            %27 = alloca [16 x i8], align 16
            %28 = alloca [16 x i8], align 16
            %29 = alloca [16 x i8], align 16
            %30 = alloca [16 x i8], align 16
            %31 = alloca [16 x i8], align 16
            %32 = alloca [16 x i8], align 16
            %33 = alloca [16 x i8], align 16
            %34 = alloca [16 x i8], align 16
            %35 = alloca [16 x i8], align 16
            %36 = alloca [16 x i8], align 16
            %37 = alloca [16 x i8], align 16
            %38 = alloca [16 x i8], align 16
            %39 = alloca [16 x i8], align 16
            %40 = alloca [16 x i8], align 16
            %41 = alloca [16 x i8], align 16
            %42 = alloca [16 x i8], align 16
            %43 = alloca [16 x i8], align 16
            %44 = alloca [16 x i8], align 16
            %45 = alloca [16 x i8], align 16
            %46 = alloca [16 x i8], align 16
            %47 = alloca [16 x i8], align 16
            %48 = alloca [16 x i8], align 16
            %49 = alloca [16 x i8], align 16
            %50 = alloca [16 x i8], align 16
            %51 = alloca [16 x i8], align 16
            %52 = alloca [16 x i8], align 16
            %53 = alloca [16 x i8], align 16
            %54 = alloca [16 x i8], align 16
            %55 = alloca [16 x i8], align 16
            %56 = alloca [16 x i8], align 16
            %57 = alloca [16 x i8], align 16
            %58 = alloca [16 x i8], align 16
            %59 = alloca [16 x i8], align 16
            %60 = alloca [16 x i8], align 16
            %61 = alloca [16 x i8], align 16
            %62 = alloca [16 x i8], align 16
            %63 = alloca [16 x i8], align 16
            %64 = alloca [16 x i8], align 16
            %65 = alloca [16 x i8], align 16
            %66 = alloca [16 x i8], align 16
            %67 = alloca [16 x i8], align 16
            %68 = alloca [16 x i8], align 16
            %69 = alloca [16 x i8], align 16
            %70 = alloca [16 x i8], align 16
            %71 = alloca [16 x i8], align 16
            %72 = alloca [16 x i8], align 16
            %73 = alloca [16 x i8], align 16
            %74 = alloca [16 x i8], align 16
            %75 = alloca [16 x i8], align 16
            %76 = alloca [16 x i8], align 16
            %77 = alloca [16 x i8], align 16
            %78 = alloca [16 x i8], align 16
            %79 = alloca [16 x i8], align 16
            %80 = alloca [16 x i8], align 16
            %81 = alloca [16 x i8], align 16
            %82 = alloca [16 x i8], align 16
            %83 = alloca [16 x i8], align 16
            %84 = alloca [16 x i8], align 16
            %85 = alloca [16 x i8], align 16
            %86 = alloca [16 x i8], align 16
            %87 = alloca [16 x i8], align 16
            %88 = alloca [16 x i8], align 16
            %89 = alloca [16 x i8], align 16
            %90 = alloca [16 x i8], align 16
            %91 = alloca [16 x i8], align 16
            %92 = alloca [16 x i8], align 16
            %93 = alloca [16 x i8], align 16
            %94 = alloca [16 x i8], align 16
            %95 = alloca [16 x i8], align 16
            %96 = alloca [16 x i8], align 16
            %97 = alloca [16 x i8], align 16
            %98 = alloca [16 x i8], align 16
            %99 = alloca [16 x i8], align 16
            %100 = alloca [16 x i8], align 16
            %101 = alloca [16 x i8], align 16
            %102 = alloca [16 x i8], align 16
            %103 = alloca [16 x i8], align 16
            %104 = alloca [16 x i8], align 16
            %105 = alloca [16 x i8], align 16
            %106 = alloca [16 x i8], align 16
            %107 = alloca [16 x i8], align 16
            %108 = alloca [16 x i8], align 16
            %109 = alloca [16 x i8], align 16
            %110 = alloca [16 x i8], align 16
            %111 = alloca [16 x i8], align 16
            %112 = alloca [16 x i8], align 16
            %113 = alloca [16 x i8], align 16
            %114 = alloca [16 x i8], align 16
            %115 = alloca [16 x i8], align 16
            %116 = alloca [16 x i8], align 16
            %117 = alloca [16 x i8], align 16
            %118 = alloca [16 x i8], align 16
            %119 = alloca [16 x i8], align 16
            %120 = alloca [16 x i8], align 16
            %121 = alloca [16 x i8], align 16
            %122 = alloca [16 x i8], align 16
            %123 = alloca [16 x i8], align 16
            %124 = alloca [16 x i8], align 16
            %125 = alloca [16 x i8], align 16
            %126 = alloca [16 x i8], align 16
            %127 = alloca [16 x i8], align 16
            %128 = alloca [16 x i8], align 16
            %129 = alloca [16 x i8], align 16
            %130 = alloca [16 x i8], align 16
            %131 = alloca [16 x i8], align 16
            %132 = alloca [16 x i8], align 16
            %133 = alloca [16 x i8], align 16
            %134 = alloca [16 x i8], align 16
            %135 = alloca [16 x i8], align 16
            %136 = alloca [16 x i8], align 16
            %137 = alloca [16 x i8], align 16
            %138 = alloca [16 x i8], align 16
            %139 = alloca [16 x i8], align 16
            %140 = alloca [16 x i8], align 16
            %141 = alloca [16 x i8], align 16
            %142 = alloca [16 x i8], align 16
            %143 = alloca [16 x i8], align 16
            %144 = alloca [16 x i8], align 16
            %145 = alloca [16 x i8], align 16
            %146 = alloca [16 x i8], align 16
            %147 = alloca [16 x i8], align 16
            %148 = alloca [16 x i8], align 16
            %149 = alloca [16 x i8], align 16
            %150 = alloca [16 x i8], align 16
            %151 = alloca [16 x i8], align 16
            %152 = alloca [16 x i8], align 16
            %153 = alloca [16 x i8], align 16
            %154 = alloca [16 x i8], align 16
            %155 = alloca [16 x i8], align 16
            %156 = alloca [16 x i8], align 16
            %157 = alloca [16 x i8], align 16
            %158 = alloca [16 x i8], align 16
            %159 = alloca [16 x i8], align 16
            %160 = alloca [16 x i8], align 16
            %161 = alloca [16 x i8], align 16
            %162 = alloca [16 x i8], align 16
            %163 = alloca [16 x i8], align 16
            %164 = alloca [16 x i8], align 16
            %165 = alloca [16 x i8], align 16
            %166 = alloca [16 x i8], align 16
            %167 = alloca [16 x i8], align 16
            %168 = alloca [16 x i8], align 16
            %169 = alloca [16 x i8], align 16
            %170 = alloca [16 x i8], align 16
            %171 = alloca [16 x i8], align 16
            %172 = alloca [16 x i8], align 16
            %173 = alloca [16 x i8], align 16
            %174 = alloca [16 x i8], align 16
            %175 = alloca [16 x i8], align 16
            %176 = alloca [16 x i8], align 16
            %177 = alloca [16 x i8], align 16
            %178 = alloca [16 x i8], align 16
            %179 = alloca [16 x i8], align 16
            %180 = alloca [16 x i8], align 16
            %181 = alloca [16 x i8], align 16
            %182 = alloca [16 x i8], align 16
            %183 = alloca [16 x i8], align 16
            %184 = alloca [16 x i8], align 16
            %185 = alloca [16 x i8], align 16
            %186 = alloca [16 x i8], align 16
            %187 = alloca [16 x i8], align 16
            %188 = alloca [16 x i8], align 16
            %189 = alloca [16 x i8], align 16
            %190 = alloca [16 x i8], align 16
            %191 = alloca [16 x i8], align 16
            %192 = alloca [16 x i8], align 16
            %193 = alloca [16 x i8], align 16
            %194 = alloca [16 x i8], align 16
            %195 = alloca [16 x i8], align 16
            %196 = alloca [16 x i8], align 16
            %197 = alloca [16 x i8], align 16
            %198 = alloca [16 x i8], align 16
            %199 = alloca [16 x i8], align 16
            %200 = alloca [16 x i8], align 16
            %201 = alloca [16 x i8], align 16
            %202 = alloca [16 x i8], align 16
            %203 = alloca [16 x i8], align 16
            %204 = alloca [16 x i8], align 16
            %205 = alloca [16 x i8], align 16
            %206 = alloca [16 x i8], align 16
            %207 = alloca [16 x i8], align 16
            %208 = alloca [16 x i8], align 16
            %209 = alloca [16 x i8], align 16
            %210 = alloca [16 x i8], align 16
            %211 = alloca [16 x i8], align 16
            %212 = alloca [16 x i8], align 16
            %213 = alloca [16 x i8], align 16
            %214 = alloca [16 x i8], align 16
            %215 = alloca [16 x i8], align 16
            %216 = alloca [16 x i8], align 16
            %217 = alloca [16 x i8], align 16
            %218 = alloca [16 x i8], align 16
            %219 = alloca [16 x i8], align 16
            %220 = alloca [16 x i8], align 16
            %221 = alloca [16 x i8], align 16
            %222 = alloca [16 x i8], align 16
            %223 = alloca [16 x i8], align 16
            %224 = alloca [16 x i8], align 16
            %225 = alloca [16 x i8], align 16
            %226 = alloca [16 x i8], align 16
            %227 = alloca [16 x i8], align 16
            %228 = alloca [16 x i8], align 16
            %229 = alloca [16 x i8], align 16
            %230 = alloca [16 x i8], align 16
            %231 = alloca [16 x i8], align 16
            %232 = alloca [16 x i8], align 16
            %233 = alloca [16 x i8], align 16
            %234 = alloca [16 x i8], align 16
            %235 = alloca [16 x i8], align 16
            %236 = alloca [16 x i8], align 16
            %237 = alloca [16 x i8], align 16
            %238 = alloca [16 x i8], align 16
            %239 = alloca [16 x i8], align 16
            %240 = alloca [16 x i8], align 16
            %241 = alloca [16 x i8], align 16
            %242 = alloca [16 x i8], align 16
            %243 = alloca [16 x i8], align 16
            %244 = alloca [16 x i8], align 16
            %245 = alloca [16 x i8], align 16
            %246 = alloca [16 x i8], align 16
            %247 = alloca [16 x i8], align 16
            %248 = alloca [16 x i8], align 16
            %249 = alloca [16 x i8], align 16
            %250 = alloca [16 x i8], align 16
            %251 = alloca [16 x i8], align 16
            %252 = alloca [16 x i8], align 16
            %253 = alloca [16 x i8], align 16
            %254 = alloca [16 x i8], align 16
            %255 = alloca [16 x i8], align 16
            %256 = alloca [16 x i8], align 16
            %257 = alloca [16 x i8], align 16
            %258 = alloca [16 x i8], align 16
            %259 = alloca [16 x i8], align 16
            %260 = alloca [16 x i8], align 16
            %261 = alloca [16 x i8], align 16
            %262 = alloca [16 x i8], align 16
            %263 = alloca [16 x i8], align 16
            %264 = alloca [16 x i8], align 16
            %265 = alloca [16 x i8], align 16
            %266 = alloca [16 x i8], align 16
            %267 = alloca [16 x i8], align 16
            %268 = alloca [16 x i8], align 16
            %269 = alloca [16 x i8], align 16
            %270 = alloca [16 x i8], align 16
            %271 = alloca [16 x i8], align 16
            %272 = alloca [16 x i8], align 16
            %273 = alloca [16 x i8], align 16
            %274 = alloca [16 x i8], align 16
            %275 = alloca [16 x i8], align 16
            %276 = alloca [16 x i8], align 16
            %277 = alloca [16 x i8], align 16
            %278 = alloca [16 x i8], align 16
            %279 = alloca [16 x i8], align 16
            %280 = alloca [16 x i8], align 16
            %281 = alloca [16 x i8], align 16
            %282 = alloca [16 x i8], align 16
            %283 = alloca [16 x i8], align 16
            %284 = alloca [16 x i8], align 16
            %285 = alloca [16 x i8], align 16
            %286 = alloca [16 x i8], align 16
            %287 = alloca [16 x i8], align 16
            %288 = alloca [16 x i8], align 16
            %289 = alloca [16 x i8], align 16
            %290 = alloca [16 x i8], align 16
            %291 = alloca [16 x i8], align 16
            %292 = alloca [16 x i8], align 16
            %293 = alloca [16 x i8], align 16
            %294 = alloca [16 x i8], align 16
            %295 = alloca [16 x i8], align 16
            %296 = alloca [16 x i8], align 16
            %297 = alloca [16 x i8], align 16
            %298 = alloca [16 x i8], align 16
            %299 = alloca [16 x i8], align 16
            %300 = alloca [16 x i8], align 16
            %301 = alloca [16 x i8], align 16
            %302 = alloca [16 x i8], align 16
            %303 = alloca [16 x i8], align 16
            %304 = alloca [16 x i8], align 16
            %305 = alloca [16 x i8], align 16
            %306 = alloca [16 x i8], align 16
            %307 = alloca [16 x i8], align 16
            %308 = alloca [16 x i8], align 16
            %309 = alloca [16 x i8], align 16
            %310 = alloca [16 x i8], align 16
            %311 = alloca [16 x i8], align 16
            %312 = alloca [16 x i8], align 16
            %313 = alloca [16 x i8], align 16
            %314 = alloca [16 x i8], align 16
            %315 = alloca [16 x i8], align 16
            %316 = alloca [16 x i8], align 16
            %317 = alloca [16 x i8], align 16
            %318 = alloca [16 x i8], align 16
            %319 = alloca [16 x i8], align 16
            %320 = alloca [16 x i8], align 16
            %321 = alloca [16 x i8], align 16
            %322 = alloca [16 x i8], align 16
            %323 = alloca [16 x i8], align 16
            %324 = alloca [16 x i8], align 16
            %325 = alloca [16 x i8], align 16
            %326 = alloca [16 x i8], align 16
            %327 = alloca [16 x i8], align 16
            %328 = alloca [16 x i8], align 16
            %329 = alloca [16 x i8], align 16
            %330 = alloca [16 x i8], align 16
            %331 = alloca [16 x i8], align 16
            %332 = alloca [16 x i8], align 16
            %333 = alloca [16 x i8], align 16
            %334 = alloca [16 x i8], align 16
            %335 = alloca [16 x i8], align 16
            %336 = alloca [16 x i8], align 16
            %337 = alloca [16 x i8], align 16
            %338 = alloca [16 x i8], align 16
            %339 = alloca [16 x i8], align 16
            %340 = alloca [16 x i8], align 16
            %341 = alloca [16 x i8], align 16
            %342 = alloca [16 x i8], align 16
            %343 = alloca [16 x i8], align 16
            %344 = alloca [16 x i8], align 16
            %345 = alloca [16 x i8], align 16
            %346 = alloca [16 x i8], align 16
            %347 = alloca [16 x i8], align 16
            %348 = alloca [16 x i8], align 16
            %349 = alloca [16 x i8], align 16
            %350 = alloca [16 x i8], align 16
            %351 = alloca [16 x i8], align 16
            %352 = alloca [16 x i8], align 16
            %353 = alloca [16 x i8], align 16
            %354 = alloca [16 x i8], align 16
            %355 = alloca [16 x i8], align 16
            %356 = alloca [16 x i8], align 16
            %357 = alloca [16 x i8], align 16
            %358 = alloca [16 x i8], align 16
            %359 = alloca [16 x i8], align 16
            %360 = alloca [16 x i8], align 16
            %361 = alloca [16 x i8], align 16
            %362 = alloca [16 x i8], align 16
            %363 = alloca [16 x i8], align 16
            %364 = alloca [16 x i8], align 16
            %365 = alloca [16 x i8], align 16
            %366 = alloca [16 x i8], align 16
            %367 = alloca [16 x i8], align 16
            %368 = alloca [16 x i8], align 16
            %369 = alloca [16 x i8], align 16
            %370 = alloca [16 x i8], align 16
            %371 = alloca [16 x i8], align 16
            %372 = alloca [16 x i8], align 16
            %373 = alloca [16 x i8], align 16
            %374 = alloca [16 x i8], align 16
            %375 = alloca [16 x i8], align 16
            %376 = alloca [16 x i8], align 16
            %377 = alloca [16 x i8], align 16
            %378 = alloca [16 x i8], align 16
            %379 = alloca [16 x i8], align 16
            %380 = alloca [16 x i8], align 16
            %381 = alloca [16 x i8], align 16
            %382 = alloca [16 x i8], align 16
            %383 = alloca [16 x i8], align 16
            %384 = alloca [16 x i8], align 16
            %385 = alloca [16 x i8], align 16
            %386 = alloca [16 x i8], align 16
            %387 = alloca [16 x i8], align 16
            %388 = alloca [16 x i8], align 16
            %389 = alloca [16 x i8], align 16
            %390 = alloca [16 x i8], align 16
            %391 = alloca [16 x i8], align 16
            %392 = alloca [16 x i8], align 16
            %393 = alloca [16 x i8], align 16
            %394 = alloca [16 x i8], align 16
            %395 = alloca [16 x i8], align 16
            %396 = alloca [16 x i8], align 16
            %397 = alloca [16 x i8], align 16

In [13]:
print_raw("aarch64", "o3")

======================================================================
 aarch64  o3
======================================================================

=== [scalar/encrypt] speck_probe::speck::backend::scalar::encrypt_block::scalar_encrypt_block_64_128
   stos:   0 alloca, >= 0 B
   sterta: 0 wywolan, >= 0 B

=== [scalar/encrypt_inflight] speck_probe::speck::backend::scalar::encrypt_block::scalar_encrypt_block_inflight_64_128
   stos:   0 alloca, >= 0 B
   sterta: 0 wywolan, >= 0 B

=== [scalar/decrypt] speck_probe::speck::backend::scalar::decrypt_block::scalar_decrypt_block_64_128
   stos:   0 alloca, >= 0 B
   sterta: 0 wywolan, >= 0 B

=== [neon/encrypt] speck_probe::speck::backend::aarch64::neon::encrypt_block::neon_encrypt_block_64_128
   stos:   0 alloca, >= 0 B
   sterta: 0 wywolan, >= 0 B

=== [neon/encrypt_inflight] speck_probe::speck::backend::aarch64::neon::encrypt_block::neon_encrypt_block_inflight_64_128
   stos:   0 alloca, >= 0 B
   sterta: 0 wywolan, >= 0 B

=== [neon/decrypt] speck_probe::speck::backend::aarch64::neon::decrypt_block::neon_decrypt_block_64_128
   stos:   0 alloca, >= 0 B
   sterta: 0 wywolan, >= 0 B